export const GET_FLATDETAILS_REQUEST = "GET_FLATDETAILS_REQUEST"
export const GET_FLATDETAILS_SUCCESS = "GET_FLATDETAILS_SUCCESS"
export const GET_FLATDETAILS_FAILURE = "GET_FLATDETAILS_FAILURE"

export const GETSINGLE_FLATDETAILS_REQUEST = "GETSINGLE_FLATDETAILS_REQUEST"
export const GETSINGLE_FLATDETAILS_SUCCESS = "GETSINGLE_FLATDETAILS_SUCCESS"
export const GETSINGLE_FLATDETAILS_FAILURE = "GETSINGLE_FLATDETAILS_FAILURE"